services:
  - type: web
    name: student-marketplace-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
